### ISSUE TITLE
query regarding search by parameter

### ISSUE THREAD

**Issue by Darkmift** [semperry/swapi#4]
Hi,

according to docs this will fetch the rsd2...and this works.
``https://www.swapi.tech/api/people/?name=r2``

however this format fetches the planet list instead
https://www.swapi.tech/api/planets/?name=Tatooine

Edit:
After reviewing the router code I see this is the way.
(which is weird since the doc example should not be working...)
https://www.swapi.tech/api/planets/?search=Tatooine

**Comment by rc-devpipeline** [comment]
Thanks for bringing this up. There should be a section explaining the "search" parameter, as well as the custom fields for each endpoint. Both ways are by design.

**Comment by semperry** [comment]
Thanks for bringing this up. There should be a section explaining the actual term "search" as a parameter, as well as the custom fields for each endpoint. Both ways are by design. I'll verify though, but this looks fine to me. Thanks again.
